In [25]:
import numpy as np
import pandas as pd

In [27]:
Data = np.load('wave_DongHai.npz', encoding = 'latin1') 

In [28]:
for key in Data.files:
    array = Data[key]
    print(f"{key}: {array.shape}")

data: (30187, 90, 1)


In [71]:
Data.files
waveData = Data['data']
waveData.shape

(30187, 90, 1)

In [35]:
wavaPd = pd.DataFrame(waveData[0])

In [49]:
fullData = np.load('swh_EastHai_Wave3_Other2_Wind_2proced_Time.npy', encoding = 'latin1', allow_pickle=True) 
print(type(fullData))
print(fullData)

<class 'numpy.ndarray'>
{'latitude': [33.0, 32.0, 31.0, 30.0, 29.0, 28.0, 27.0, 26.0, 25.0], 'longitude': [123.0, 123.5, 124.0, 124.5, 125.0, 125.5, 126.0, 126.5, 127.0, 127.5], 'data': array([[[[1.64352950e+00, 5.24973778e+00, 2.84026592e+02, ...,
          3.35168051e+02, 3.45791941e+02, 9.02880000e+05],
         [1.75780587e+00, 5.39260410e+00, 2.84393855e+02, ...,
          3.35394800e+02, 3.43352970e+02, 9.02880000e+05],
         [1.89623949e+00, 5.51147113e+00, 2.85575373e+02, ...,
          3.35015709e+02, 3.40463558e+02, 9.02880000e+05],
         ...,
         [1.81419894e+00, 5.47015472e+00, 2.90343881e+02, ...,
          3.32142565e+02, 3.19001707e+02, 9.02880000e+05],
         [1.97678982e+00, 5.41773276e+00, 2.91630074e+02, ...,
          3.31025579e+02, 3.22874398e+02, 9.02880000e+05],
         [2.42283628e+00, 5.71607678e+00, 2.91879031e+02, ...,
          3.28768543e+02, 3.24516859e+02, 9.02880000e+05]],

        [[1.54470437e+00, 5.19044544e+00, 2.83525591e+02, ...,
   

In [58]:
data_dic = fullData.item()
print(type(data_dic))
latitude = data_dic['latitude']
longitude = data_dic['longitude']
data = data_dic['data']
key = data_dic['value_name']

<class 'dict'>
{'latitude': [33.0, 32.0, 31.0, 30.0, 29.0, 28.0, 27.0, 26.0, 25.0], 'longitude': [123.0, 123.5, 124.0, 124.5, 125.0, 125.5, 126.0, 126.5, 127.0, 127.5], 'data': array([[[[1.64352950e+00, 5.24973778e+00, 2.84026592e+02, ...,
          3.35168051e+02, 3.45791941e+02, 9.02880000e+05],
         [1.75780587e+00, 5.39260410e+00, 2.84393855e+02, ...,
          3.35394800e+02, 3.43352970e+02, 9.02880000e+05],
         [1.89623949e+00, 5.51147113e+00, 2.85575373e+02, ...,
          3.35015709e+02, 3.40463558e+02, 9.02880000e+05],
         ...,
         [1.81419894e+00, 5.47015472e+00, 2.90343881e+02, ...,
          3.32142565e+02, 3.19001707e+02, 9.02880000e+05],
         [1.97678982e+00, 5.41773276e+00, 2.91630074e+02, ...,
          3.31025579e+02, 3.22874398e+02, 9.02880000e+05],
         [2.42283628e+00, 5.71607678e+00, 2.91879031e+02, ...,
          3.28768543e+02, 3.24516859e+02, 9.02880000e+05]],

        [[1.54470437e+00, 5.19044544e+00, 2.83525591e+02, ...,
          3.

In [59]:
print(latitude, longitude, key)

[33.0, 32.0, 31.0, 30.0, 29.0, 28.0, 27.0, 26.0, 25.0] [123.0, 123.5, 124.0, 124.5, 125.0, 125.5, 126.0, 126.5, 127.0, 127.5] ['swh', 'mwp', 'sst', 'msl', 'wsd', 'dwi', 'mwd', 'time']


In [87]:
print(data.shape)
print(data[1].shape)
time_steps = np.zeros(len(data))
for i in range(len(data)):
    time_steps[i] = data[i][0][0][7]
    
print(time_steps)

(30187, 9, 10, 8)
(9, 10, 8)
[ 902880.  902886.  902892. ... 1083984. 1083990. 1083996.]


In [77]:
waveData.shape

(30187, 90, 1)

In [83]:
len(waveData)
waveHeight1 = np.zeros(len(waveData))
for i in range(len(waveData)):
    waveHeight1[i] = waveData[i][0][0]

In [84]:
waveData

array([[[1.6435295 ],
        [1.75780587],
        [1.89623949],
        ...,
        [2.51366129],
        [2.46024866],
        [2.4250324 ]],

       [[1.68039285],
        [1.81270872],
        [1.94557363],
        ...,
        [2.290991  ],
        [2.24997073],
        [2.21655842]],

       [[1.55929284],
        [1.73513883],
        [1.90282783],
        ...,
        [2.27342209],
        [2.23240182],
        [2.20604845]],

       ...,

       [[1.41375894],
        [1.38223013],
        [1.32668714],
        ...,
        [1.95040219],
        [1.92377423],
        [1.89208206]],

       [[1.12313844],
        [1.26607995],
        [1.40673439],
        ...,
        [1.88146354],
        [1.87149848],
        [1.86316703]],

       [[0.96467757],
        [1.03900716],
        [1.1002678 ],
        ...,
        [1.86774116],
        [1.90368074],
        [1.95301598]]])

In [85]:
waveHeight1

array([1.6435295 , 1.68039285, 1.55929284, ..., 1.41375894, 1.12313844,
       0.96467757])